const SET_LOCATION = 'SET_LOCATION';
const GET_5_DAILY_FORECAST = 'GET_5_DAILY_FORECAST';
const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
const CHANGE_FAVORITE_STATUS = 'CHANGE_FAVORITE_STATUS';

export { SET_LOCATION, GET_5_DAILY_FORECAST, GET_CURRENT_WEATHER, CHANGE_FAVORITE_STATUS };