const SET_LOCATION = "SET_LOCATION";
const GET_5_DAILY_FORECAST = "GET_5_DAILY_FORECAST";
const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
const SET_ALERT = "SET_ALERT";
const REMOVE_ALERT = "REMOVE_ALERT";
const GET_FAVORITES = 'GET_FAVORITES';
const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export {
  SET_LOCATION,
  GET_5_DAILY_FORECAST,
  GET_CURRENT_WEATHER,
  SET_ALERT,
  REMOVE_ALERT,
  GET_FAVORITES,
  REMOVE_FROM_FAVORITES
};
